# Generated by Django 2.2.17 on 2022-09-26 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import web_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(choices=[('AUTH', 'AUTH'), ('CUT', 'CUT'), ('CUX', 'CUX'), ('NTNU', 'NTNU'), ('SHENKAR', 'SHENKAR'), ('UPAT', 'UPAT')], max_length=15)),
                ('password', models.CharField(max_length=500)),
                ('role', models.CharField(choices=[('INSTRUCTOR', 'INSTRUCTOR'), ('STUDENT', 'STUDENT')], max_length=15)),
                ('surname', models.CharField(max_length=50)),
                ('c_register_task_id', models.CharField(default='', max_length=100)),
                ('c_reset_task_id', models.CharField(default='', max_length=100)),
                ('ts_entry_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('ts_last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_level', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('b1', 'b1'), ('b2', 'b2'), ('c1', 'c1'), ('c2', 'c2'), ('d1', 'd1'), ('d2', 'd2'), ('PROFESSOR', 'PROFESSOR'), ('ASSOCIATE PROFESSOR', 'ASSOCIATE PROFESSOR')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='images')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=20)),
                ('width', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('technique', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('art_type', models.CharField(max_length=200)),
                ('user_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAndLevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionSpaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VR_Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(max_length=20000)),
                ('name', models.CharField(max_length=200)),
                ('rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_request_count', models.IntegerField(default=0)),
                ('reset_code', models.CharField(max_length=50)),
                ('ts_expiration_reset', models.DateTimeField(default=web_app.models.ResetPassword.calculate_expiration, null=True)),
                ('ts_reset', models.DateTimeField(null=True)),
                ('ts_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorExhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(default=' ', max_length=2000)),
                ('user_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('description', models.CharField(max_length=500, null=True)),
                ('ts_last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('artwork_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Artwork')),
                ('exhibition_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.OutdoorExhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('space_assign', models.CharField(choices=[('Separate Spaces', 'Separate Spaces'), ('Shared Rooms', 'Shared Rooms'), ('Shared Floor', 'Shared Floor')], max_length=15)),
                ('message', models.CharField(default=' ', max_length=2000)),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.CharField(choices=[('Temporary Stored', 'Temporary Stored'), ('Accepting Artworks', 'Accepting Artworks'), ('Ready to be Assessed', 'Ready to be Assessed'), ('Assessment Started', 'Assessment Started'), ('Assessed', 'Assessed'), ('Published', 'Published')], max_length=30)),
                ('ts_last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructor_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedExhibitionStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_app.Exhibition')),
                ('student_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedExhibitionInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_app.Exhibition')),
                ('instructor_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=50)),
                ('ts_activation', models.DateTimeField(default=None, null=True)),
                ('frequent_request_count', models.IntegerField(default=0)),
                ('ts_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
