# Generated by Django 2.2.17 on 2022-09-27 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coadvisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Exhibition')),
                ('instructor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('instructor_fk', 'assignment_fk')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Exhibition')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student_fk', 'assignment_fk')},
            },
        ),
    ]
