# Generated by Django 2.2.17 on 2022-09-28 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_assessment_coadvisors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coadvisors',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coadvisors',
            name='assignment_fk',
        ),
        migrations.RemoveField(
            model_name='coadvisors',
            name='instructor_fk',
        ),
        migrations.AddField(
            model_name='assignedexhibitioninstructor',
            name='assignment_fk',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='web_app.Exhibition'),
        ),
        migrations.AddField(
            model_name='assignedexhibitionstudents',
            name='assignment_fk',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='web_app.Exhibition'),
        ),
        migrations.AlterField(
            model_name='assignedexhibitioninstructor',
            name='instructor_fk',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedexhibitionstudents',
            name='student_fk',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignedexhibitioninstructor',
            unique_together={('instructor_fk', 'assignment_fk')},
        ),
        migrations.AlterUniqueTogether(
            name='assignedexhibitionstudents',
            unique_together={('student_fk', 'assignment_fk')},
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Coadvisors',
        ),
        migrations.RemoveField(
            model_name='assignedexhibitioninstructor',
            name='exhibition_fk',
        ),
        migrations.RemoveField(
            model_name='assignedexhibitionstudents',
            name='exhibition_fk',
        ),
    ]
