# Generated by Django 2.2.17 on 2022-09-28 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20220928_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedexhibitionstudents',
            name='assignment_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_app.Exhibition'),
        ),
        migrations.AlterField(
            model_name='assignedexhibitionstudents',
            name='student_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
