version: '3'

volumes:
  creams-db-data:

networks:
  web:
    external: true

services:
  creams-postgres:
    image: postgres
    restart: always
    volumes:
      - creams-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
     - "5432:5432"
    networks:
      - web
  creams-server:
    build: .
    command: bash -c "python3 manage.py makemigrations web_app && python3 manage.py migrate && python3 manage.py collectstatic --no-input && python3 manage.py runserver 0.0.0.0:10000"
    container_name: creams-server
    env_file:
      - ./django_variables.env
    volumes:
      - .:/code
      - ./config/nginx/certs/:/etc/certs
      - ./staticfiles/:/code/staticfiles
    ports:
        - "10000:10000"
    depends_on:
      - creams-postgres
      - creams-rabbit
    stdin_open: true
    tty: true
    networks:
      - web
  creams-rabbit:
    image: "rabbitmq:3-management"
    hostname: "creams-rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "16672:15672"
      - "6672:5672"
    labels:
      NAME: "creams-rabbit"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
  creams-celery:
    build: .
    env_file:
      - ./django_variables.env
    working_dir: /code
    command:  ./init_celery.sh
    links:
      - creams-rabbit
    volumes:
      - .:/code
    ports:
      - "6555:5555"
    networks:
      - web
